
INSERT INTO blogful_articles (title, content, date_published)
VALUES
     ('Attempting to Build IKEA Furniture Without Instructions', 'Carpentry may have proven too difficult for Ethan to master. Perhaps assembling IKEA furniture is more his speed. Too bad he lost the instructions.', '2020-06-09T13:00')
     ('There Is Something Horribly Wrong with This Picture...', 'Do not look to closely at these pictures. If you can see them... they can see you too. And then they will know exactly where to find you.', '2020-06-08T13:00')
     ('Ethan Roasts Mark for 15 Minutes Straight', 'Mark is a bad bad man who needs to be exposed for his sins. Ethan is just the right big bold boy to roast Mark to a crisp!', '2020-06-07T13:00')
     ('Mark Teaches Ethan to Read with Hooked on Phonics', 'Ethan has always had a dream of learning the mysteries of the written word. With the BIG BRAIN of Mark, he might just make a breakthrough.', '2020-06-06T13:00')
     ('Reacting to Your Hilarious Green Screen Memes', 'As you know, the first annual Unus Annus Green Screen Competition took place just last week and now it is time to review the winners!', '2020-06-05T13:00')
     ('Morphing Our Bodies Into Superhero Poses', 'You hear that? That call in the night? The call for help? The call for justice? The call for a hero? WE will answer that call.', '2020-06-04T13:00')
     ('Crushing Watermelons Betwixt Our Mighty Thighs', 'We return once again to showcase our feats of incredible strength. Gaze upon our mammoth hams as we quash these juicy gourds.', '2020-06-03T13:00')
     ('BLACK LIVES MATTER. Resources and How You Can Help in the Description.', 'Black Lives Matter. Let us work together as a community to make a real difference.', '2020-06-02T13:00')
     ('2 Complete Amateurs Enter a Body Building Competition', 'Welcome to the First Annual Unus Annus Body Building Competition Extravaganza! Who will wear the crown of best bod?', '2020-06-01T13:00')
     ('Tearing a Phone Book in Half with Our Huge Manly Muscles', 'One half Unus, the other half Annus. Two halves of one whole. One soul. One Phone book now torn in half. We have big big muscles, we know.', '2020-05-31T13:00')
     ('DIY Wine', `Bonjour! Je vois que vous êtes aussi une personne de culture qui aime les belles choses de la vie. Rejoignez-nous! Rejoignez-nous alors que nous prenons part au necteur des dieux qu'est le vin.`, '2020-05-30T13:00')
     ('Only Watch from 2:15 to 6:11 --- DO NOT WATCH ANY OTHER PART OF THIS VIDEO', `Annus has officially been declared the WINNER! Please skip to 2:15 to view Annus's glorious appreciation segment and cease watching at exactly 6:11. DO NOT WATCH ANY OTHER PART OF THE VIDEO. DO NOT.`, '2020-05-29T13:00')
     ('Only UNUS-es And ANNUS-es May Watch This Video', `You already know that you're welcome here.`, '2020-05-28T13:00')
     ('DO NOT OPEN UNTIL 2080', 'Some secrets should stay buried...', '2020-05-27T13:00')
     ('The Unus Annus Confessional Booth', 'We called upon you: our lovely followers to confess your deepest, darkest secrets to us... and what we found was more shocking than any mere mortal can bare.', '2020-05-26T13:00')
     ('We Have the Best Bellies on Youtube', 'Our bellies are the best bellies. Anyone who disagrees is WRONG with the FACT and will have their heads squooshed betwixt our glorious tummies. Also we learn to belly dance.', '2020-05-25T13:00')
     ('DIY YouTube', 'The Boys Make a YouTube... Quarantine will make anyone crazy.', '2020-05-24T13:00')
     ('We Play the Newlywed Game While Consuming That Which Will Kill the Other', `Mark and Ethan test how well they really know each other with the classic 1960's sensation known as the Newlywed Game. Also we consume each other's poisons.`, '2020-05-23T13:00')
     ('Mark Cooks Blindfolded While Ethan Guides Him Through FaceTime', `Umm... you probably shouldn't attempt to do this at home. In fact don't. Definitely do not do the this that we are doing. Definitely do not do. Don't.`, '2020-05-22T13:00')
     ('Harnessing Our Yodeling Power to End The World As We Know It', 'You hear that? Off in the distance? That, my friends, is the sound of two gods screaming into the ether. It is the first sound in the morning and the last sound at night. It is the call to end all calls. It is... THE YODEL.', '2020-05-21T13:00')